apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment-v2
  labels:
    app: devops
    version: v2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
      version: v2.0
  template:
    metadata:
      labels:
        app: devops
        version: v2.0
    spec:
      containers:
      - name: devops-demo
        image: drehnstrom/devops-demo:v2.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"